// File automatically generated by protoc-gen-sol v0.2.0-2-g782a9bc
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0 <8.0.0;
pragma experimental ABIEncoderV2;

import "@lazyledger/protobuf3-solidity-lib/contracts/ProtobufLib.sol";
import "./message.proto.sol";
import "./verification.proto.sol";

